import type { Metadata } from 'next'
import { Inter,Space_Grotesk } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar';
import Home2, { Home } from './amazon/page';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });
const SpaceGrotesk=Space_Grotesk({ subsets: ['latin'] ,weight:['300','400','500','600','700']});
export const metadata: Metadata = {
  title: 'price tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        
        
        <Footer/>
        </body>
    </html>
  )
}










